# Generated by Django 4.1.4 on 2022-12-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='new_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
