# Generated by Django 4.1.4 on 2022-12-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0002_usermodel_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='new_field',
        ),
    ]
