# Generated by Django 4.1.4 on 2022-12-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0003_remove_usermodel_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
